const actions = {
  GET_ALL_TODOS: "GET_ALL_TODOS",
  GET_ALL_TODOS_ERROR: "GET_ALL_TODOS_ERROR",
  GET_ALL_TODOS_SUCCESS: "GET_ALL_TODOS_SUCCESS",

  SET_TOOD: "SET_TODO",
  SET_TODO_ERROR: "SET_TODO_ERROR",
  SET_TODO_SUCCESS: "SET_TODO_SUCCESS",

  DELETE_TODO: "DELETE_TODO",
  DELETE_TODO_ERROR: "DELETE_TODO_ERROR",
  DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",

  UPDATE_TODO_STATUS: "UPDATE_TODO_STATUS",
  UPDATE_TODO_STATUS_ERROR: "UPDATE_TODO_STATUS_ERROR",
  UPDATE_TODO_STATUS_SUCCESS: "UPDATE_TODO_STATUS_SUCCESS",

  DELETE_ALL_TODOS: "DELETE_ALL_TODOS",
  DELETE_ALL_TODOS_ERROR: "DELETE_ALL_TODOS_ERROR",
  DELETE_ALL_TODOS_SUCCESS: "DELETE_ALL_TODOS_SUCCESS",
};

export default actions;
